server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/color?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath: db/color.sql
    initialization-mode: always

  elasticsearch:
    rest:
      uris: http://localhost:9200

mybatis-plus:
  global-config:
    db-config:
      # 表名前缀
      table-prefix: tb_
      # id生成策略 数据库自增
      id-type: auto
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logback配置
logging:
  pattern:
    console: '%d -%msg%n'
  file:
    path: 'E:\project\own\gradle-project'
    name: 'gradle.log'
  level:
    root: info
